create extension if not exists vector;
create extension if not exists pgcrypto;

create table if not exists documents (
  id uuid primary key default gen_random_uuid(),
  source_url text not null unique,
  source_title text not null,
  source_domain text not null,
  content_hash text not null,
  status text not null default 'ready',
  fetched_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists document_chunks (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references documents(id) on delete cascade,
  source_url text not null,
  source_title text not null,
  chunk_index integer not null,
  chunk_text text not null,
  token_estimate integer not null default 0,
  embedding vector not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  unique (document_id, chunk_index)
);

alter table if exists document_chunks
  alter column embedding type vector
  using embedding::vector;

create table if not exists chat_logs (
  id uuid primary key default gen_random_uuid(),
  question text not null,
  answer text not null,
  answer_status text not null,
  fallback_triggered boolean not null default false,
  escalation_suggested boolean not null default false,
  confidence_score real not null default 0,
  category text not null default 'other',
  heuristic_flags text[] not null default '{}'::text[],
  top_sources jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists analytics_events (
  id uuid primary key default gen_random_uuid(),
  event_type text not null,
  question text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists documents_source_domain_idx on documents (source_domain);
create index if not exists document_chunks_document_id_idx on document_chunks (document_id);
create index if not exists chat_logs_created_at_idx on chat_logs (created_at desc);
create index if not exists analytics_events_created_at_idx on analytics_events (created_at desc);

drop function if exists match_document_chunks(vector(1536), int, float);
drop function if exists match_document_chunks(vector, int, float);
drop function if exists match_document_chunks(vector, int, float, text, text);

create or replace function match_document_chunks (
  query_embedding vector,
  match_count int default 6,
  match_threshold float default 0.45,
  embedding_provider text default null,
  embedding_model text default null
)
returns table (
  id uuid,
  document_id uuid,
  source_url text,
  source_title text,
  chunk_index integer,
  chunk_text text,
  similarity float
)
language sql
stable
as $$
  select
    document_chunks.id,
    document_chunks.document_id,
    document_chunks.source_url,
    document_chunks.source_title,
    document_chunks.chunk_index,
    document_chunks.chunk_text,
    1 - (document_chunks.embedding <=> query_embedding) as similarity
  from document_chunks
  where 1 - (document_chunks.embedding <=> query_embedding) > match_threshold
    and (
      embedding_provider is null
      or document_chunks.metadata ->> 'embedding_provider' = embedding_provider
    )
    and (
      embedding_model is null
      or document_chunks.metadata ->> 'embedding_model' = embedding_model
    )
  order by document_chunks.embedding <=> query_embedding
  limit match_count;
$$;

-- This schema intentionally keeps the embedding column unbounded so local models
-- with different dimensions can be swapped without changing the table type again.
-- document_chunks.metadata stores the active embedding provider and model so
-- retrieval only searches vectors generated by the currently configured setup.
-- Re-ingest the docs whenever you switch embedding providers or embedding models.
-- For larger datasets, add an approximate index after you commit to a single
-- embedding dimension and cast accordingly in the index expression.
